language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
  - PINS="ke:https://github.com/dinosaure/ke.git" 
  matrix:
  - PACKAGE="encore" OCAML_VERSION=4.05 TESTS=false EXTRA_DEPS="mirage-xen"
  - PACKAGE="encore" OPAM_VERBOSE=1 ALCOTEST_VERBOSE=1 OCAML_VERSION=4.06 TESTS=true
  - PACKAGE="encore" OCAML_VERSION=4.07 TESTS=false EXTRA_DEPS="mirage-solo5"
  - PACKAGE="encore" OPAM_VERBOSE=1 ALCOTEST_VERBOSE=1 OCAML_VERSION=4.07 TESTS=true
