language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  matrix:
  - PACKAGE="encore" PINS="git:https://github.com/dinosaure/ocaml-git.git \
                           git-http:https://github.com/dinosaure/ocaml-git.git \
                           git-unix:https://github.com/dinosaure/ocaml-git.git" OCAML_VERSION=4.06 TESTS=true
